### ISSUE TITLE
Procedure for creating updates to AmberTools23?

### ISSUE THREAD

**Issue by dacase** [conda-forge/ambertools-feedstock#117]
### Comment:

Hi: Pull requests #113 and #116 will require changes to the AmberTools23 source.  There seem to be two possible ways to update the conda packages:
1. have `ambertools-feedstock` access the update.xxx files at `ambermd.org`, starting from the original (23.0) AmberTools tar file.
2. Create an updated, complete tar file, and have the conda build script pull that.
3. something else??

Option 2 seems easier, but I don't remember doing that in the past.  I'm happy to create the updated tar file.

**Comment by mattwthompson** [comment]
Building from an official release asset (i.e. a single tarball) is preferred - if there are updates to a package, they're usually reflected in a new release with a different version. `conda-forge` might have a policy that states this preference more strongly, I can't find the official stance on it.

Applying patches to an existing release is possible but not elegant. You can see some examples of this in `recipe/patches/`

**Comment by jaimergp** [comment]
We have been ok with getting the updates as patches for a while (see beginning of build.sh). Full archives are preferred, though.

**Comment by hainm** [comment]
I think full archives are just easier, just a matter of providing a new link.

**Comment by mikemhenry** [comment]
Patches work, but some of the improvements I think will be useful to the whole AmberTools community so creating a `23.1` version I think would be best.

**Comment by mattwthompson** [comment]
@dacase I've started this in #118 with some verbose comments that are hopefully useful for understanding the changes. No guarantees it works on the first try 🤞

**Comment by swails** [comment]
The challenge with using full archives is that they can only be created and uploaded by Dave (compare that to update files which can be raised as a PR by any developer, then merged/synced by Dave).

I know I'm late to this conversation (I was on vacation last week), but I don't think it's a good idea to split how we update source code in conda-forge vs. how everyone else gets it.  I don't think it's any easier to do it that way given that `build.sh` already encodes the logic to update to a specific version.  You could argue that you get increased safety by checking the hash of the updated package, but the counterargument is that you're no longer guaranteeing that the source tarball matches what non-conda users will have (not to mention the 1.5 GB tarballs that will need to be stored for each version on the server, which will start to be impactful if/when hosting is moved to cloud infrastructure).

**Comment by swails** [comment]
I think it's worth trying to update the conda-forge build script to remove pre-cythonized files and just rebuild pytraj entirely.

**Comment by hainm** [comment]
> I think it's worth trying to update the conda-forge build script to remove pre-cythonized files and just rebuild pytraj entirely.

I agree with @swails about this. (I've thought about that too).

- remove pre-cythonized .cpp files
- update pytraj/scripts/base_setup.py to change is_release=True to is_release=False
- need to pin cython >= 0.29.35
