### ISSUE TITLE
MPI builds

### ISSUE THREAD

**Issue by njzjz** [conda-forge/ambertools-feedstock#132]
### Comment:

It seems to me that MPI is not enabled in this recipe. I'd like to know if there is any specific reason for it, or if I can contribute to enable MPI.

**Comment by jaimergp** [comment]
Yea, just lack of volunteer time to implement it _and_ maintain it. Same with CUDA stuff. Ambertools takes a while to build so each attempt is very time consuming if things stop working due to a change somewhere.
