### ISSUE TITLE
Ambertools should depend on ParmEd

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/ambertools-feedstock#21]
Instead of bundling ParmEd with AmberTools, add the already existing package to the requirements, so downstream packages can use both if needed without clobbering issues (e.g. https://github.com/omnia-md/conda-recipes/pull/1011#issuecomment-579337182).

**Comment by hainm** [comment]
does that mean when user use AT 20, it's not really AT 20 (because the ParmEd version is different).

**Comment by jaimergp** [comment]
Yes, that's one of the things we need to figure out... Should we pin the ParmEd version this package relies on? Or stick to shipping ParmEd within AmberTools and simply mark ParmEd as incompatible with this package (via [`run_constrained`](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#run-constrained)?

**Comment by hainm** [comment]
I don't have a good suggestion here. Ping @dacase and @swails

**Comment by jaimergp** [comment]
A heads up on the coming changes for this issue:

* @swails released ParmEd 3.3.0, which is the same exact commit AmberTools 20 vendored
* I am going to patch the installation here to remove the vendored ParmEd and use the conda-forge package instead
* It will be pinned with >=3.3.0, <4.0

ETA this week or next

**Comment by swails** [comment]
That'll make my life much easier.
