### ISSUE TITLE
AmberTools 20 is released

### ISSUE THREAD

**Issue by jchodera** [conda-forge/ambertools-feedstock#31]
Now that [AmberTools 20 has been released](https://ambermd.org/GetAmber.php#ambertools), we should update the recipe!

@dacase: Could you put a copy of the `AmberTools20.tar.bz2` up at https://ambermd.org/downloads/ like you did for `AmberTools19.tar.bz2`? We can use the automated update mechanism to keep the package current with patch releases after that!

We'll then be able to update [this line](https://github.com/conda-forge/ambertools-feedstock/blob/master/recipe/meta.yaml#L11), as well as address #27.

**Comment by jaimergp** [comment]
We have been testing the RCs for weeks now! Check #30. I got the new URL as well. It will be updated today.

**Comment by jchodera** [comment]
Awesome, thanks!
