### ISSUE TITLE
ambertools package vendors packmol

### ISSUE THREAD

**Issue by swails** [conda-forge/ambertools-feedstock#61]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

AmberTools installs and includes a `packmol` binary (an old one) which will overwrite the packmol binary installed from the actual packmol package.  So you'll see something like the following:

```
(test-packmol) swails@Batman ~ $ conda list | grep -e ambertools -e packmol
# packages in environment at /scratch2/anaconda3/envs/test-packmol:
ambertools                20.15                    pypi_0    pypi
packmol                   20.2.2               h92ddd45_0    conda-forge
packmol-memgen            1.1.0rc0                 pypi_0    pypi
(test-packmol) swails@Batman ~ $ packmol -v

################################################################################

 PACKMOL - Packing optimization for the automated generation of
 starting configurations for molecular dynamics simulations.
 
                           Included as part of Packmol Memgen
                                                              Version 18.169 

################################################################################

  Packmol must be run with: packmol < inputfile.inp 

  Userguide at: www.ime.unicamp.br/~martinez/packmol 

  Reading input file... (Control-C aborts)
^C
```

As you can see, conda thinks it installed packmol 20.2.2, but the ambertools package really silently overwrote it with its own copy.

Just like we're switching the ambertools package to depend on parmed (instead of vendoring), we should do the same to packmol, especially if this is going to be an indirect dependency (which it is likely to be given its relationship to openff).

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by jaimergp** [comment]
Thanks for the report @swails 

I'll create a PR to address this over the following days!
