### ISSUE TITLE
PowerPC builds?

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/ambertools-feedstock#7]
Hi, could it be possible to obtain `ppc64le` builds for this package?

I have checked the host requirements and some do not have a PowerPC package yet, though. Namely:

* [x] `openmp` is not needed! `osx` requires `llvmp-openmp`
* [x] `bc` - Submitted [PR here](https://github.com/conda-forge/bc-feedstock/pull/9). Tests are passing, we are now waiting for review.
* [x] `tcsh` - Submitted [PR here](https://github.com/conda-forge/tcsh-feedstock/pull/1). Tests are passing, we are now waiting for review.

Thanks!

**Comment by simonbray** [comment]
Hi @jaimergp, I haven't done this before but I don't have any objection. Would you like to submit a PR?

**Comment by jaimergp** [comment]
We'll need to create recipes for the build dependencies first. I'll see if I can get in touch with the maintainers in those feedstocks and get back to this one once those are ready! Thanks for your collaboration!

**Comment by jaimergp** [comment]
I have submitted PRs when possible. We should have the dependencies available soon!

**Comment by isuruf** [comment]
You should remove `openmp` for linux (`libgomp` is bundled with libgcc-ng) and have `llvm-openmp` for osx.

**Comment by jaimergp** [comment]
Thanks @isuruf !
