### ISSUE TITLE
We need to work on creating a conda package for AmberTools22, which will be released soon

### ISSUE THREAD

**Issue by dacase** [conda-forge/ambertools-feedstock#81]
### Comment:

The release of AmberTools22 should be ready later this month (April, 2022).  We have release candidates ready, but I'd like to find out what problems (if any) we will find in updating the current conda packages.  Here is the updated URL

   https://ambermd.org/downloads/AmberTools22.02apr22.tar.bz2

In the ideal world, one could substitute the new URL for the existing one in the `meta.yaml` file.  I don't see any obvious problems in `build.sh`, but the code changes are pretty big, so something is likely to break....For sure, the three patch files invoked after downloading the source are unlikely to apply cleanly.

Unfortunately, I am not much of a conda or conda-forge person.  I edited build.sh to skip the `update_amber` step, and tried `conda build recipe`.  Pretty early on I encountered a version problem with cpptraj:
```
+ rm /Users/case/conda-bld/ambertools_1649863164081/work/AmberTools/src/cpptraj/src/xdrfile/version
rm: /Users/case/conda-bld/ambertools_1649863164081/work/AmberTools/src/cpptraj/src/xdrfile/version: No such file or directory
```
I could try to track this down, but it seems likely that someone (@jaimergp  @simonbray ?) would be much more likely to know what to do here, and in whatever pops up next.  But let me know how I can help, if needed.

...thanks!....dac

**Comment by mattwthompson** [comment]
> the code changes are pretty big

Is there a changelog for the release compiled somewhere? I couldn't find anything in a newer tarball of the source code (https://ambermd.org/downloads/AmberTools22.15apr22.tar.bz2) and the website understandably only lists the patches in version 21. If not, I expect we'll still be able to hunt down any behavior changes with RC packages built.

**Comment by dacase** [comment]
No: we have no comprehensive ChangeLog.  As you correctly note, there are lots of changes, but all pass CI before being committed to the release branch.  We can also run the CI suite on a draft conda package.  Let me know what I can do to help, especially with validation/testing of a new build.  (We build and test this code outside of conda-forge on dozens of environments -- see e.g. https://gitlab.ambermd.org/amber/amber/-/wikis/Singularity-Amber22

**Comment by mattwthompson** [comment]
Thanks for the reply - no follow-up action to request now. We'll just wait for/help with the RC packages here; pre-release conda builds are a pretty low-friction way for downstream developers and users to test things out during the RC period.

The interest in a changelog is more for behavior changes in the tools, i.e. molecules that antechamber might produce different results on. I have no doubt that the code will be self-consistent, building and passing tests on all platforms, etc. If for some reason we get strange behavior or different results we'll report back.

**Comment by dacase** [comment]
Here is the final source for AmberTools22:
      https://ambermd.org/downloads/AmberTools22jlmrcc.tar.bz2
(This is the same as for AmberTools21, except for the 21->22 swap.)

We haven't announced this yet, but I won't allow any changes unless something is a real show-stopper.  We can delay the announcement of the availability of the conda package if that is needed; the errors I've seen I can live with.  Support within conda for Apple M1 machines can certainly wait, since we don't have a verified source-code install recipe for this, independent of conda-forge.

Let me know what you think the best thing to do here is.  I'd like to verify the final `conda install` command syntax before advertising it, but I think we could let users have at this.  Critical projects can continue to pin their requirements to ambertools=21, and be no worse off than they are now.  But comments and suggestions are welcome here -- I'm a conda user, but have only created fairly simple packages myself.

**Comment by jaimergp** [comment]
Yes, I think we are fine. I'll give you some packages you can try locally in that PR.
