### ISSUE TITLE
Description of the license for AmberTools needs improvement

### ISSUE THREAD

**Issue by dacase** [conda-forge/ambertools-feedstock#9]
Issue: The license for AmberTools is not correctly described.

The README says that the AmberTools license is GPL, but this is too simple.  AmberTools is a collection of packages, some GPL, some key ones LGPL, others are BSD, some are public domain.  The AmberTools distribution has a LICENSE file (in the AmberTools folder) which explains things carefully.

A key point is that anything that needs to be linked (including all the compiled python modules) are LGPL.

**Comment by jchodera** [comment]
@isuruf: You recently had some great insight about properly communicating the license information for OpenMM. Do you have any suggestions on the best approach here? The most restrictive license is GPL, but as @dacase notes, anything that needs to be linked here is LGPL.

**Comment by jaimergp** [comment]
@dacase, the specification I was referring to [can be found here](https://spdx.github.io/spdx-spec/v2-draft/SPDX-license-expressions/).

The idea is that the `license` field uses this expression. `license_file` can be a list of relative paths in the source with the main license, and the vendored ones (if any). [See this example for reference](https://github.com/conda-forge/napari-feedstock/blob/378ef86c0fab6549dceac042c58c004930aa9134/recipe/meta.yaml#L110-L117).

**Comment by jaimergp** [comment]
We can add it as part of the v23 release, yes.
